### ISSUE TITLE
unicode errors when creating a node

### ISSUE THREAD

**Issue by frueter** [dbr/tabtabtab-nuke#17]
I started getting the below errors every time I create a node with tabtabtab.
Any ideas what might be causing this?

```
Traceback (most recent call last):
  File "/ohufx/pipeline/tools/nuke/python/tabtabtab.py", line 479, in update
    self.things_model.set_filter(text)
  File "/ohufx/pipeline/tools/nuke/python/tabtabtab.py", line 245, in set_filter
    self.update()
  File "/ohufx/pipeline/tools/nuke/python/tabtabtab.py", line 259, in update
    if nonconsec_find(filtertext, uiname.lower(), anchored=True):
  File "/ohufx/pipeline/tools/nuke/python/tabtabtab.py", line 126, in nonconsec_find
    if "".join(haystack).startswith(needle.lstrip(" ")):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 38: ordinal not in range(128)
```

**Comment by frueter** [comment]
I just found [NateScarelet's branch](https://github.com/dbr/tabtabtab-nuke/pull/16) which fixes this.
